package de.rochlitz.mygarderobe.jpa.entity;

// Generated 30.08.2012 09:22:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageOutfit generated by hbm2java
 */
@Entity
@Table(name = "image_outfit", catalog = "mygarderobe")
public class ImageOutfit implements java.io.Serializable {

    private Integer recordId;
    private Image image;
    private Outfit outfit;
    private String topPosition;
    private String leftPosition;
    private int zindex;

    public ImageOutfit() {
    }

    public ImageOutfit(Image image, Outfit outfit, String topPosition, String leftPosition, int zindex) {
	this.image = image;
	this.outfit = outfit;
	this.topPosition = topPosition;
	this.leftPosition = leftPosition;
	this.zindex = zindex;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "record_id", unique = true, nullable = false)
    public Integer getRecordId() {
	return this.recordId;
    }

    public void setRecordId(Integer recordId) {
	this.recordId = recordId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "image_id", nullable = false)
    public Image getImage() {
	return this.image;
    }

    public void setImage(Image image) {
	this.image = image;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "outfit_id", nullable = false)
    public Outfit getOutfit() {
	return this.outfit;
    }

    public void setOutfit(Outfit outfit) {
	this.outfit = outfit;
    }

    @Column(name = "top_position", nullable = false, length = 56)
    public String getTopPosition() {
	return this.topPosition;
    }

    public void setTopPosition(String topPosition) {
	this.topPosition = topPosition;
    }

    @Column(name = "left_position", nullable = false, length = 56)
    public String getLeftPosition() {
	return this.leftPosition;
    }

    public void setLeftPosition(String leftPosition) {
	this.leftPosition = leftPosition;
    }

    @Column(name = "zindex", nullable = false)
    public int getZindex() {
	return this.zindex;
    }

    public void setZindex(int zindex) {
	this.zindex = zindex;
    }

}
