package de.rochlitz.mygarderobe.jpa.entity;

// Generated 30.08.2012 09:22:52 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "mygarderobe")
public class Image implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -5378155837831884402L;
    private Integer imageId;
    private User user;
    private String filename;
    private String name;
    private Set<ImageOutfit> imageOutfits = new HashSet<ImageOutfit>(0);
    private Set<ImageTag> imageTags = new HashSet<ImageTag>(0);

    public Image() {
    }

    public Image(User user, String filename, String name) {
	this.user = user;
	this.filename = filename;
	this.name = name;
    }

    public Image(User user, String filename, String name, Set<ImageOutfit> imageOutfits, Set<ImageTag> imageTags) {
	this.user = user;
	this.filename = filename;
	this.name = name;
	this.imageOutfits = imageOutfits;
	this.imageTags = imageTags;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "image_id", unique = true, nullable = false)
    public Integer getImageId() {
	return this.imageId;
    }

    public void setImageId(Integer imageId) {
	this.imageId = imageId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
	return this.user;
    }

    public void setUser(User user) {
	this.user = user;
    }

    @Column(name = "filename", nullable = false)
    public String getFilename() {
	return this.filename;
    }

    public void setFilename(String filename) {
	this.filename = filename;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
    public Set<ImageOutfit> getImageOutfits() {
	return this.imageOutfits;
    }

    public void setImageOutfits(Set<ImageOutfit> imageOutfits) {
	this.imageOutfits = imageOutfits;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
    public Set<ImageTag> getImageTags() {
	return this.imageTags;
    }

    public void setImageTags(Set<ImageTag> imageTags) {
	this.imageTags = imageTags;
    }

}
