package de.rochlitz.mygarderobe.jpa.entity;

// Generated 30.08.2012 09:22:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OutfitTag generated by hbm2java
 */
@Entity
@Table(name = "outfit_tag", catalog = "mygarderobe")
public class OutfitTag implements java.io.Serializable {

    private Integer recordId;
    private Tag tag;
    private Outfit outfit;

    public OutfitTag() {
    }

    public OutfitTag(Tag tag, Outfit outfit) {
	this.tag = tag;
	this.outfit = outfit;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "record_id", unique = true, nullable = false)
    public Integer getRecordId() {
	return this.recordId;
    }

    public void setRecordId(Integer recordId) {
	this.recordId = recordId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tag_id", nullable = false)
    public Tag getTag() {
	return this.tag;
    }

    public void setTag(Tag tag) {
	this.tag = tag;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "outfit_id", nullable = false)
    public Outfit getOutfit() {
	return this.outfit;
    }

    public void setOutfit(Outfit outfit) {
	this.outfit = outfit;
    }

}
