package de.rochlitz.mygarderobe.jpa.entity;

// Generated 30.08.2012 09:22:52 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "mygarderobe")
public class Roles implements java.io.Serializable {

    private RolesId id;

    public Roles() {
    }

    public Roles(RolesId id) {
	this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "username", column = @Column(name = "username", length = 64)),
	    @AttributeOverride(name = "userRole", column = @Column(name = "user_role", length = 64)),
	    @AttributeOverride(name = "roleGroup", column = @Column(name = "role_group", length = 64)) })
    public RolesId getId() {
	return this.id;
    }

    public void setId(RolesId id) {
	this.id = id;
    }

}
