package de.rochlitz.mygarderobe.jpa.entity;

// Generated 30.08.2012 09:22:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolesId generated by hbm2java
 */
@Embeddable
public class RolesId implements java.io.Serializable {

    private String username;
    private String userRole;
    private String roleGroup;

    public RolesId() {
    }

    public RolesId(String username, String userRole, String roleGroup) {
	this.username = username;
	this.userRole = userRole;
	this.roleGroup = roleGroup;
    }

    @Column(name = "username", length = 64)
    public String getUsername() {
	return this.username;
    }

    public void setUsername(String username) {
	this.username = username;
    }

    @Column(name = "user_role", length = 64)
    public String getUserRole() {
	return this.userRole;
    }

    public void setUserRole(String userRole) {
	this.userRole = userRole;
    }

    @Column(name = "role_group", length = 64)
    public String getRoleGroup() {
	return this.roleGroup;
    }

    public void setRoleGroup(String roleGroup) {
	this.roleGroup = roleGroup;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof RolesId))
	    return false;
	RolesId castOther = (RolesId) other;

	return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null && castOther.getUsername() != null && this.getUsername().equals(
		castOther.getUsername())))
		&& ((this.getUserRole() == castOther.getUserRole()) || (this.getUserRole() != null && castOther.getUserRole() != null && this.getUserRole()
			.equals(castOther.getUserRole())))
		&& ((this.getRoleGroup() == castOther.getRoleGroup()) || (this.getRoleGroup() != null && castOther.getRoleGroup() != null && this
			.getRoleGroup().equals(castOther.getRoleGroup())));
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
	result = 37 * result + (getUserRole() == null ? 0 : this.getUserRole().hashCode());
	result = 37 * result + (getRoleGroup() == null ? 0 : this.getRoleGroup().hashCode());
	return result;
    }

}
